---
title: "Graphs"
author: "Autumn Dunn"
date: "2/21/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed
```{r}
library(ggpubr)
library(ggplot2)
library(readxl)
library(dplyr)
library(lubridate)
```

Functions Used
```{r}
#Fix days that will not be read as date
fix_day = Vectorize(function(day) {
  if (day %in% 1:9) return(paste0("0", day))
  return(day)
})

#Theme for Graphs
mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top") #alternative: legend.position + legend.justification
```

Upload Data
```{r}
Nitrogen <- read_excel("../Data/Nitrogen.xlsx")
Phosphorus <- read_excel("../Data/Phosphorus.xlsx")
TotalSuspendedSolids <- read_excel("../Data/TotalSuspendedSolids.xlsx")
YSI <- read_excel("../Data/YSI.xlsx")
FecalColiform <- read_excel("../Data/FecalColiform.xlsx")
```

Processing Data
```{r}
#combine and isolate SWAMP data
SWAMP_Nitrogen<- Nitrogen %>%
  select(`Month`, `Day`, `Year`, `Site`, `Total N (ug/L)`, `NH4-N (ug/L)`, `NOX`) %>% 
  filter(Site %in% c("WT1", "WT2", "WT3", "WT5", "BR5", "DS1"))

SWAMP_Phosphorus<- Phosphorus %>%
  select(`Month`, `Day`, `Year`, `Site`, `UTP`) %>% 
  filter(Site %in% c("WT1", "WT2", "WT3", "WT5", "BR5", "DS1"))

SWAMP_FecalColiform<- FecalColiform %>%
  select(`Month`, `Day`, `Year`, `Site`, `FC`) %>% 
  filter(Site %in% c("WT1", "WT2", "WT3", "WT5", "BR5", "DS1"))

SWAMP_TotalSuspendedSolids<- TotalSuspendedSolids %>%
  select(`Month`, `Day`, `Year`, `Site`, `TSS (mg/L)`) %>% 
  filter(Site %in% c("WT1", "WT2", "WT3", "WT5", "BR5", "DS1"))

SWAMP_YSI<- YSI %>%
  select(`Month`, `Day`, `Year`, `Site`, `pH`, `Temp C`) %>% 
  filter(Site %in% c("WT1", "WT2", "WT3", "WT5", "BR5", "DS1"))

SWAMP_Data<- bind_rows(SWAMP_Nitrogen, SWAMP_Phosphorus, SWAMP_FecalColiform, SWAMP_TotalSuspendedSolids, SWAMP_YSI)

SWAMP_means <- SWAMP_Data %>% 
  group_by(`Month`, `Day`, `Year`, `Site`) %>% 
summarise(Mean_TN = mean(`Total N (ug/L)`),
          Mean_NH = mean(`NH4-N (ug/L)`),
          Mean_NOX = mean(`NOX`),
          Mean_TP = mean(`UTP`),
          Mean_FC = mean(`FC`),
          Mean_TSS = mean(`TSS (mg/L)`),
          Mean_Temp = mean(`Temp C`),
          )

ALL_SWAMP_data<- bind_rows(SWAMP_Data, SWAMP_means)
ALL_SWAMP_data$pH<- as.numeric(ALL_SWAMP_data$pH)

#Combine and Isolate Duke Garden Data
DukeGarden_Nitrogen<- Nitrogen %>%
  select(`Month`, `Day`, `Year`, `Site`, `Total N (ug/L)`, `NH4-N (ug/L)`, `NOX`) %>% 
  filter(Site %in% c("D", "S", "U", "DP1", "DP2", "DP3"))

DukeGarden_Phosphorus<- Phosphorus %>%
  select(`Month`, `Day`, `Year`, `Site`, `UTP`) %>% 
  filter(Site %in% c("D", "S", "U", "DP1", "DP2", "DP3"))

DukeGarden_FecalColiform<- FecalColiform %>%
  select(`Month`, `Day`, `Year`, `Site`, `FC`) %>% 
  filter(Site %in% c("D", "S", "U", "DP1", "DP2", "DP3"))

DukeGarden_TotalSuspendedSolids<- TotalSuspendedSolids %>%
  select(`Month`, `Day`, `Year`, `Site`, `TSS (mg/L)`) %>% 
  filter(Site %in% c("D", "S", "U", "DP1", "DP2", "DP3"))

DukeGarden_YSI<- YSI %>%
  select(`Month`, `Day`, `Year`, `Site`, `pH`, `Temp C`) %>% 
  filter(Site %in% c("D", "S", "U", "DP1", "DP2", "DP3"))

DukeGarden_Data<- bind_rows(DukeGarden_Nitrogen, DukeGarden_Phosphorus, DukeGarden_FecalColiform, DukeGarden_TotalSuspendedSolids, DukeGarden_YSI)
```

Question 1. How does SWAMP water quality compare to EPA standards?
```{r}
######   Graphs   ######

###   Nitrogen   ###

#Total Nitrogen for Phase 2 outflow SWAMP Site WT3 on a log scale
WT3_TN<-SWAMP_Data %>%
  filter(Site %in% c("WT3")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`Total N (ug/L)`), colour = Site)) +
  geom_abline(aes(intercept=log(800), slope=0, lty='EPA Standard of total nitrogen for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Total Nitrogen (ug/L)") +
  ggtitle("Total Nitrogen for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

ggplotly(WT3_TN)

#Ammonium for Phase 2 outflow SWAMP Site WT3 on a log scale
WT3_NH<-SWAMP_Data %>%
  filter(Site %in% c("WT3")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`NH4-N (ug/L)`) , colour = Site)) +
  geom_abline(aes(intercept=log(20), slope=0, lty='EPA Standard of ammonium for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Ammonium (ug/L)") +
  ggtitle("Ammonium for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Nitrous Oxide for Phase 2 outflow SWAMP Site WT3 on a log scale
WT3_NOX<-SWAMP_Data %>%
  filter(Site %in% c("WT3")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`NOX`), colour = Site)) +
  geom_abline(aes(intercept=log(345), slope=0, lty='EPA Standard of nitrous oxide for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Nitrous Oxide (ug/L)") +
  ggtitle("Nitrous Oxide for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Total Nitrogen for Phase 2 outflow SWAMP Site WT5 on a log scale
WT5_TN<-SWAMP_Data %>%
  filter(Site %in% c("WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`Total N (ug/L)`), colour = Site)) +
  geom_abline(aes(intercept=log(800), slope=0, lty='EPA Standard of total nitrogen for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Total Nitrogen (ug/L)") +
  ggtitle("Total Nitrogen for Phase 2 Outflow SWAMP Site WT5 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Ammonium for Phase 2 outflow SWAMP Site WT3 on a log scale
WT5_NH<-SWAMP_Data %>%
  filter(Site %in% c("WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`NH4-N (ug/L)`), colour = Site)) +
  geom_abline(aes(intercept=log(20), slope=0, lty='EPA Standard of ammonium for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Ammonium (ug/L)") +
  ggtitle("Ammonium for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Nitrous Oxides for Phase 2 outflow SWAMP Site WT5 on a log scale
WT5_NOX<-SWAMP_Data %>%
  filter(Site %in% c("WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`NOX`), colour = Site)) +
  geom_abline(aes(intercept=log(345), slope=0, lty='EPA Standard of nitrous oxide for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Nitrous Oxide (ug/L)") +
  ggtitle("Nitrous Oxide for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Total Nitrogen for Phase 3 outflow SWAMP Site WT2 on a log scale
WT2_TN<-SWAMP_Data %>%
  filter(Site %in% c("WT2")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`Total N (ug/L)`), colour = Site)) +
  geom_abline(aes(intercept=log(800), slope=0, lty='EPA Standard of total nitrogen for Ecoregion IX'), col = "black") +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Total Nitrogen (ug/L)") +
  ggtitle("Total Nitrogen for Phase 2 Outflow SWAMP Site WT2 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Ammonium for Phase 2 outflow SWAMP Site WT2 on a log scale
WT2_NH<-SWAMP_Data %>%
  filter(Site %in% c("WT2")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`NH4-N (ug/L)`), colour = Site)) +
  geom_abline(aes(intercept=log(20), slope=0, lty='EPA Standard of ammonium for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Ammonium (ug/L)") +
  ggtitle("Ammonium for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Nitrous Oxide for Phase 2 outflow SWAMP Site WT2 on a log scale
WT2_NOX<-SWAMP_Data %>%
  filter(Site %in% c("WT2")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`NOX`), colour = Site)) +
  geom_abline(aes(intercept=log(345), slope=0, lty='EPA Standard of nitrous oxide for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Nitrous Oxide (ug/L)") +
  ggtitle("Nitrous Oxide for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Total Nitrogen for 3 Sites
TN_outflow<-ALL_SWAMP_data %>%
  filter(Site %in% c("WT2" , "WT3", "WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`Total N (ug/L)`))) +
      geom_smooth(se=TRUE, method = "loess", span=0.2, color= "black") +
      xlab("Year") +
      ylab("Total Nitrogen (ug/L)") +
      ggtitle("Total Nitrogen for SWAMP Outflow" ) +
  mytheme +
  facet_wrap(~Site, nrow = 3) +
stat_summary(fun = mean, aes(shape=""), geom = "line", color = "Red", alpha = 0.4, show.legend = TRUE) +
      scale_shape_manual("Mean", values="Mean") +
  guides(shape = guide_legend(override.aes = list(linetype = 1, size = 1, alpha = 0.4, color="red"))) +
geom_hline(aes(yintercept=log(800), color="EPA Standard of Total Nitrogen for Ecoregion IX"), lty=2, show.legend = TRUE) +
      scale_color_manual("", values = c("black")) +
      guides(color = guide_legend(override.aes = list(linetype = 2, size = 1, alpha = 1)))

#Ammonium for 3 sites
NH_outflow<-ALL_SWAMP_data %>%
  filter(Site %in% c("WT2" , "WT3", "WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`NH4-N (ug/L)`))) +
      geom_smooth(se=TRUE, method = "loess", span=0.2, color= "black") +
      xlab("Year") +
      ylab("Ammonium (ug/L)") +
      ggtitle("Ammonium for SWAMP Outflow" ) +
  mytheme +
  facet_wrap(~Site, nrow = 3) +
stat_summary(fun = mean, aes(shape=""), geom = "line", color = "Red", alpha = 0.4, show.legend = TRUE) +
      scale_shape_manual("Mean", values="Mean") +
  guides(shape = guide_legend(override.aes = list(linetype = 1, size = 1, alpha = 0.4, color="red"))) +
geom_hline(aes(yintercept=log(20), color="EPA Standard of Ammonium for Ecoregion IX"), lty=2, show.legend = TRUE) +
      scale_color_manual("", values = c("black")) +
      guides(color = guide_legend(override.aes = list(linetype = 2, size = 1, alpha = 1)))

#Nitrous Oxide for 3 sites
NOX_outflow<-ALL_SWAMP_data %>%
  filter(Site %in% c("WT2" , "WT3", "WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`NOX`))) +
      geom_smooth(se=TRUE, method = "loess", span=0.2, color= "black") +
      xlab("Year") +
      ylab("Nitrous Oxide (ug/L)") +
      ggtitle("Nitrous Oxide for SWAMP Outflow" ) +
  mytheme +
  facet_wrap(~Site, nrow = 3) +
stat_summary(fun = mean, aes(shape=""), geom = "line", color = "Red", alpha = 0.4, show.legend = TRUE) +
      scale_shape_manual("Mean", values="Mean") +
  guides(shape = guide_legend(override.aes = list(linetype = 1, size = 1, alpha = 0.4, color="red"))) +
geom_hline(aes(yintercept=log(345), color="EPA Standard of Nitrous Oxide for Ecoregion IX"), lty=2, show.legend = TRUE) +
      scale_color_manual("", values = c("black")) +
      guides(color = guide_legend(override.aes = list(linetype = 2, size = 1, alpha = 1)))

###   Phosphorus   ###

#Total Phosphorus for Phase 2 outflow SWAMP Site WT3 on a log scale
WT3_TP<-SWAMP_Data %>%
  filter(Site %in% c("WT3")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`UTP`), colour = Site)) +
  geom_abline(aes(intercept=log(30), slope=0, lty='EPA Standard of total phosphorus for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Total Phosphorus (ug/L)") +
  ggtitle("Total Phosphorus for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Total Phosphrous for Phase 2 outflow SWAMP Site WT5 on a log scale
WT5_TP<-SWAMP_Data %>%
  filter(Site %in% c("WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`UTP`), colour = Site)) +
  geom_abline(aes(intercept=log(30), slope=0, lty='EPA Standard of total phosphorus for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Total Phosphorus (ug/L)") +
  ggtitle("Total Phosphorus for Phase 2 Outflow SWAMP Site WT5 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Total Phosphorus for Phase 3 outflow SWAMP Site WT2 on a log scale
WT2_TP<-SWAMP_Data %>%
  filter(Site %in% c("WT2")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`UTP`), colour = Site)) +
  geom_abline(aes(intercept=log(30), slope=0, lty='EPA Standard of total phosphorus for Ecoregion IX'), col = "black") +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Total Phosphorus (ug/L)") +
  ggtitle("Total Phosphorus for Phase 2 Outflow SWAMP Site WT2 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Total Phosphorus for 3 sites
TP_outflow<-ALL_SWAMP_data %>%
  filter(Site %in% c("WT2" , "WT3", "WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`UTP`))) +
      geom_smooth(se=TRUE, method = "loess", span=0.2, color= "black") +
      xlab("Year") +
      ylab("Total Phosphorus (ug/L)") +
      ggtitle("Total Phosphorus for SWAMP Outflow" ) +
  mytheme +
  facet_wrap(~Site, nrow = 3) +
stat_summary(fun = mean, aes(shape=""), geom = "line", color = "Red", alpha = 0.4, show.legend = TRUE) +
      scale_shape_manual("Mean", values="Mean") +
  guides(shape = guide_legend(override.aes = list(linetype = 1, size = 1, alpha = 0.4, color="red"))) +
geom_hline(aes(yintercept=log(30), color="EPA Standard of Total Phosphorus for Ecoregion IX"), lty=2, show.legend = TRUE) +
      scale_color_manual("", values = c("black")) +
      guides(color = guide_legend(override.aes = list(linetype = 2, size = 1, alpha = 1)))


###   Fecal Coliform   ###

#Fecal Coliform for Phase 2 outflow SWAMP Site WT3 on a log scale
WT3_FC<-SWAMP_Data %>%
  filter(Site %in% c("WT3")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`FC`), colour = Site)) +
  geom_abline(aes(intercept=log(200), slope=0, lty='EPA Standard of fecal coliform for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Fecal Coliform (colonies/100 mL)") +
  ggtitle("Fecal Coliform for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Fecal Coliform for Phase 2 outflow SWAMP Site WT5 on a log scale
WT5_FC<-SWAMP_Data %>%
  filter(Site %in% c("WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`FC`), colour = Site)) +
  geom_abline(aes(intercept=log(200), slope=0, lty='EPA Standard of fecal coliform for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Fecal Coliform (colonies/100 mL)") +
  ggtitle("Fecal Coliform for Phase 2 Outflow SWAMP Site WT5 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Fecal Coliform for Phase 3 outflow SWAMP Site WT2 on a log scale
WT2_FC<-SWAMP_Data %>%
  filter(Site %in% c("WT2")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`FC`), colour = Site)) +
  geom_abline(aes(intercept=log(200), slope=0, lty='EPA Standard of fecal coliform for Ecoregion IX'), col = "black") +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Fecal Coliform (colonies/100 mL)") +
  ggtitle("Fecal Coliform for Phase 2 Outflow SWAMP Site WT2 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Fecal Coliform for 3 sites
FC_outflow<-ALL_SWAMP_data %>%
  filter(Site %in% c("WT2" , "WT3", "WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`FC`))) +
      geom_smooth(se=TRUE, method = "loess", span=0.2, color= "black") +
      xlab("Year") +
      ylab("Fecal Coliform (colonies/100 mL)") +
      ggtitle("Fecal Coliform for SWAMP Outflow" ) +
  mytheme +
  facet_wrap(~Site, nrow = 3) +
stat_summary(fun = mean, aes(shape=""), geom = "line", color = "Red", alpha = 0.4, show.legend = TRUE) +
      scale_shape_manual("Mean", values="Mean") +
  guides(shape = guide_legend(override.aes = list(linetype = 1, size = 1, alpha = 0.4, color="red"))) +
geom_hline(aes(yintercept=log(200), color="EPA Standard of Fecal Coliform for Ecoregion IX"), lty=2, show.legend = TRUE) +
      scale_color_manual("", values = c("black")) +
      guides(color = guide_legend(override.aes = list(linetype = 2, size = 1, alpha = 1)))


###   Temperature   ###

#Temperature for Phase 2 outflow SWAMP Site WT3 on a log scale
WT3_Temp<-SWAMP_Data %>%
  filter(Site %in% c("WT3")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`Temp C`), colour = Site)) +
  geom_abline(aes(intercept=log(32), slope=0, lty='EPA Standard of temperature for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Temperature (C)") +
  ggtitle("Temperature for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Temperature for Phase 2 outflow SWAMP Site WT5 on a log scale
WT5_Temp<-SWAMP_Data %>%
  filter(Site %in% c("WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`Temp C`), colour = Site)) +
  geom_abline(aes(intercept=log(32), slope=0, lty='EPA Standard of temperature for Ecoregion IX')) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Temperature (C)") +
  ggtitle("Temperature for Phase 2 Outflow SWAMP Site WT5 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Temperature for Phase 3 outflow SWAMP Site WT2 on a log scale
WT2_Temp<-SWAMP_Data %>%
  filter(Site %in% c("WT2")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`Temp C`), colour = Site)) +
  geom_abline(aes(intercept=log(32), slope=0, lty='EPA Standard of temperature for Ecoregion IX'), col = "black") +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Temperature (C)") +
  ggtitle("Temperature for Phase 2 Outflow SWAMP Site WT2 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Temperature for 3 sites
Temp_outflow<-ALL_SWAMP_data %>%
  filter(Site %in% c("WT2" , "WT3", "WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`Temp C`))) +
      geom_smooth(se=TRUE, method = "loess", span=0.2, color= "black") +
      xlab("Year") +
      ylab("Temperature (Celcius)") +
      ggtitle("Temperature for SWAMP Outflow" ) +
  mytheme +
  facet_wrap(~Site, nrow = 3) +
stat_summary(fun = mean, aes(shape=""), geom = "line", color = "Red", alpha = 0.4, show.legend = TRUE) +
      scale_shape_manual("Mean", values="Mean") +
  guides(shape = guide_legend(override.aes = list(linetype = 1, size = 1, alpha = 0.4, color="red"))) +
geom_hline(aes(yintercept=log(32), color="EPA Standard of Temperature for Ecoregion IX"), lty=2, show.legend = TRUE) +
      scale_color_manual("", values = c("black")) +
      guides(color = guide_legend(override.aes = list(linetype = 2, size = 1, alpha = 1)))


###   pH   ###

#pH for Phase 2 outflow SWAMP Site WT3
WT3_pH<-SWAMP_Data %>%
  filter(Site %in% c("WT3")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = (`pH`), colour = Site)) +
  geom_abline(aes(intercept= (6), slope=0, lty='EPA Standard of pH for Ecoregion IX')) +
    geom_abline(aes(intercept= (9), slope=0)) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("pH") +
  ggtitle("pH for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#pH for Phase 2 outflow SWAMP Site WT5
WT5_pH<-SWAMP_Data %>%
  filter(Site %in% c("WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = (`pH`), colour = Site)) +
  geom_abline(aes(intercept=6, slope=0, lty='EPA Standard of pH for Ecoregion IX')) +
      geom_abline(aes(intercept= (9), slope=0)) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("pH") +
  ggtitle("pH for Phase 2 Outflow SWAMP Site WT5 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#pH for Phase 3 outflow SWAMP Site WT2
WT2_pH<-SWAMP_Data %>%
  filter(Site %in% c("WT2")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = (`pH`), colour = Site)) +
  geom_abline(aes(intercept=(6), slope=0, lty='EPA Standard of pH for Ecoregion IX'), col = "black") +
      geom_abline(aes(intercept= (9), slope=0)) +
  scale_linetype(name = NULL) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("pH") +
  ggtitle("pH for Phase 2 Outflow SWAMP Site WT2 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#pH for 3 sites
pH_outflow<-ALL_SWAMP_data %>%
  filter(Site %in% c("WT2" , "WT3", "WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = (`pH`))) +
      geom_line() +
      geom_smooth(se=TRUE, method = "loess", span=0.2, color= "black") +
      xlab("Year") +
      ylab("pH") +
      ggtitle("pH for SWAMP Outflow" ) +
  mytheme +
  facet_wrap(~Site, nrow = 3) +
stat_summary(fun = mean, aes(shape=""), geom = "line", color = "Red", alpha = 0.4, show.legend = TRUE) +
      scale_shape_manual("Mean", values="Mean") +
  guides(shape = guide_legend(override.aes = list(linetype = 1, size = 1, alpha = 0.4, color="red"))) +
geom_hline(aes(yintercept=(6), color="EPA Standard of pH for Ecoregion IX"), lty=2, show.legend = TRUE) +
geom_hline(aes(yintercept=(9), color="EPA Standard of pH for Ecoregion IX"), lty=2, show.legend = TRUE) +
      scale_color_manual("", values = c("black")) +
      guides(color = guide_legend(override.aes = list(linetype = c(2), size = c(1), alpha = c(1))))


###   Sediment   ###

#Total Suspended Solids for Phase 2 outflow SWAMP Site WT3 on a log scale
WT3_TSS<-SWAMP_Data %>%
  filter(Site %in% c("WT3")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`TSS (mg/L)`), colour = Site)) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Total Suspended Solids (mg/L)") +
  ggtitle("Total Suspended Solids for Phase 2 Outflow SWAMP Site WT3 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Total Suspended Solids for Phase 2 outflow SWAMP Site WT5 on a log scale
WT5_TSS<-SWAMP_Data %>%
  filter(Site %in% c("WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`TSS (mg/L)`), colour = Site)) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Total Suspended Solids (mg/L)") +
  ggtitle("Total Suspended Solids for Phase 2 Outflow SWAMP Site WT5 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Total Suspended Solids for Phase 3 outflow SWAMP Site WT2 on a log scale
WT2_TSS<-SWAMP_Data %>%
  filter(Site %in% c("WT2")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`TSS (mg/L)`), colour = Site)) +
  geom_smooth(se=TRUE) +
    xlab("Year") +
  ylab("Total Suspended Solids (mg/L)") +
  ggtitle("Total Suspended Solids for Phase 2 Outflow SWAMP Site WT2 on a log scale" ) +
  stat_summary(fun = mean, geom = "line", lwd = 1, aes(group = 1, lty = 'Mean'), 
               col = "cornsilk4", size = 3) +
  mytheme 

#Total suspended solids for 3 sites
TSS_outflow<-ALL_SWAMP_data %>%
  filter(Site %in% c("WT2" , "WT3", "WT5")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`TSS (mg/L)`))) +
      geom_smooth(se=TRUE, method = "loess", span=0.2, color= "black") +
      xlab("Year") +
      ylab("Total Suspended Solids (mg/L)") +
      ggtitle("Total Suspended Solids for SWAMP Outflow" ) +
  mytheme +
  facet_wrap(~Site, nrow = 3) +
stat_summary(fun = mean, aes(shape=""), geom = "line", color = "Red", alpha = 0.4, show.legend = TRUE) +
      scale_shape_manual("Mean", values="Mean") +
  guides(shape = guide_legend(override.aes = list(linetype = 1, size = 1, alpha = 0.4, color="red")))


## Save plots ##
saveRDS(TN_outflow, file ="../Graphs/TN_outflow.rds")
saveRDS(NH_outflow, file ="../Graphs/NH_outflow.rds")
saveRDS(NOX_outflow, file ="../Graphs/NOX_outflow.rds")
saveRDS(TP_outflow, file ="../Graphs/TP_outflow.rds")
saveRDS(pH_outflow, file ="../Graphs/pH_outflow.rds")
saveRDS(TSS_outflow, file ="../Graphs/TSS_outflow.rds")
saveRDS(Temp_outflow, file ="../Graphs/Temp_outflow.rds")
saveRDS(FC_outflow, file ="../Graphs/FC_outflow.rds")
```

Q2.
```{r}
#Inflow and Outflow sites compared
#WT1 is a control site, considered pre-treatment to SWAMP
#WT1 compared to BR5
#WT1 compared to outflow points WT2, WT3, WT5
#Provide mean, median, and yearly average

###   Nitrogen   ###

#Total Nitrogen Graphs 

TN_compare_inflow.to.outflow1<-ALL_SWAMP_data %>%
  filter(Site %in% c("WT1", "WT2" , "WT3", "WT5", "BR5", "DS1")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`Total N (ug/L)`))) +
      geom_smooth(se=TRUE, method = "loess", span=0.2, color= "black") +
      xlab("Year") +
      ylab("Total Nitrogen (ug/L)") +
      ggtitle("Total Nitrogen for 6 Duke Forest Sites" ) +
  mytheme +
  facet_wrap(~Site, nrow = 3) +
stat_summary(fun = mean, aes(shape=""), geom = "line", color = "Red", alpha = 0.4, show.legend = TRUE) +
      scale_shape_manual("Mean", values="Mean") +
  guides(shape = guide_legend(override.aes = list(linetype = 1, size = 1, alpha = 0.4, color="red"))) +
geom_hline(aes(yintercept=log(800), color="EPA Standard of Total Nitrogen for Ecoregion IX"), lty=2, show.legend = TRUE) +
      scale_color_manual("", values = c("black")) +
      guides(color = guide_legend(override.aes = list(linetype = 2, size = 1, alpha = 1)))

TN_compare_inflow.to.outflow2<-  ALL_SWAMP_data %>%
  filter(Site %in% c("WT1", "WT2" , "WT3", "WT5", "BR5", "DS1")) %>%
  mutate(date = ydm(paste0(Year, fix_day(Day), Month, sep="-"))) %>% 
ggplot(aes(x = date, y = log(`Total N (ug/L)`), colour = Site)) +
      geom_smooth(se=TRUE, method = "loess", span=0.2) +
      xlab("Year") +
      ylab("Total Nitrogen (ug/L)") +
      ggtitle("Total Nitrogen for 6 Duke Forest Sites" ) +
  mytheme +
#stat_summary(fun = mean, aes(shape=""), geom = "line", color = "Red", alpha = 0.4, show.legend = TRUE) +
#      scale_shape_manual("Mean", values="Mean") +
#  guides(shape = guide_legend(override.aes = list(linetype = 1, size = 1, alpha = 0.4, color="red"))) +
geom_hline(aes(yintercept=log(800), shape="EPA Standard of Total Nitrogen for Ecoregion IX"), lty=2, show.legend = TRUE) +
      scale_shape_manual("", values = "EPA Standard of Total Nitrogen for Ecoregion IX") +
      guides(shape = guide_legend(override.aes = list(linetype = 2, size = 1, alpha = 1)))

#save graphs
saveRDS(TN_compare_inflow.to.outflow1, file ="../Graphs/TN_compare_inflow.to.outflow1.rds")
saveRDS(TN_compare_inflow.to.outflow2, file ="../Graphs/TN_compare_inflow.to.outflow2.rds")

```
